language: cpp

compiler:
- gcc

branches: 
 only:
 - master

before_install:
- DIR=`pwd`
- sudo apt-get update -qq
- sudo apt-get install tree -y
- git clone --quiet --depth=1 --branch=bin https://github.com/manhtuvjp/test_mxe.git $HOME/mxe

script:
- NUM_JOBS=$(grep processor /proc/cpuinfo | wc -l)
- make CROSS=$HOME/mxe/usr/bin/i686-w64-mingw32.static- --jobs=$NUM_JOBS
- make install

after_success:
- git clone --quiet --depth=1 --branch=bin https://${GH_TOKEN}@github.com/manhtuvjp/Barebones-Compiler.git $HOME/bin_mxe > /dev/null
- cd $HOME
- git config --global user.email "manhtuvjp@gmail.com"
- git config --global user.name "MT"
- cd $HOME/bin_mxe
- git rm -rf \*
- for file_name in $(ls $DIR/bin); do mv $DIR/bin/file_name $DIR/bin/file_name.exe; done
- zip -rj BarebonesCompiler_master.zip $DIR/bin
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to bin"
- git push -fq origin bin > /dev/null

env:
  global:
    secure: BXmWVHs6u84Qj8WkDkHynDs3A7QQ3qQsOu87hDOfp+w2UD7vCafj+gQSC2o0fI6PRMnrqi/TpE1u8coTn9tCbaTHx5UaPj0BsldJYNoqUHfJznHJYoB2H01QK7RzdoyjrIQOjD12JBM2tqLSxPSMkEmmPw9sZ0+km4McbsdmkBI=
