language: cpp

compiler:
- gcc

branches: 
 only:
 - master

before_install:
- DIR=`pwd`
- sudo apt-get update -qq
- apt-cache search "" | grep mingw

install:
- sudo apt-get build-dep gcc-mingw-w64-x86-64 -y
- sudo apt-get install tree bison flex binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-mingw-w64 gcc-mingw-w64-base gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gfortran-mingw-w64 gfortran-mingw-w64-i686 gfortran-mingw-w64-x86-64 gnat-mingw-w64 gnat-mingw-w64-base gnat-mingw-w64-i686 gnat-mingw-w64-x86-64 mingw-w64 mingw-w64-common mingw-w64-i686-dev mingw-w64-x86-64-dev -y

script:
- NUM_JOBS=$(grep processor /proc/cpuinfo | wc -l)
# Compile for Windows:
- make CROSS=x86_64-w64-mingw32- --jobs=$NUM_JOBS
- make install
- mv $DIR/bin $DIR/bin_windows
- make clean && make clear
# Compile for Linux:
- make --jobs=$NUM_JOBS
- make install

after_success:
- git clone --quiet --depth=1 --branch=bin https://${GH_TOKEN}@github.com/manhtuvjp/Barebones-Compiler.git $HOME/bin_mxe > /dev/null
- cd $HOME
- git config --global user.email "manhtuvjp@gmail.com"
- git config --global user.name "MT"
- cd $HOME/bin_mxe
- git rm -rf \*
- for file_name in $(ls $DIR/bin_w); do mv $DIR/bin_w/$file_name $DIR/bin_w/$file_name.exe; done
- zip -rj BarebonesCompiler_master_Windows.zip $DIR/bin_w
- zip -rj BarebonesCompiler_master_Linux.zip $DIR/bin
- git add -f .
- git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to bin"
- git push -fq origin bin > /dev/null

env:
  global:
    secure: BXmWVHs6u84Qj8WkDkHynDs3A7QQ3qQsOu87hDOfp+w2UD7vCafj+gQSC2o0fI6PRMnrqi/TpE1u8coTn9tCbaTHx5UaPj0BsldJYNoqUHfJznHJYoB2H01QK7RzdoyjrIQOjD12JBM2tqLSxPSMkEmmPw9sZ0+km4McbsdmkBI=
